### ISSUE TITLE
use the bufferSize encrypt big file

### ISSUE THREAD

**Issue by vinsonpyg** [jlinoff/lock_files#5]
Will there be a problem with this?
I mainly think about encrypting large files. I think scripts should have this function, which is perfect.

bufferSize = 64 * 1024000
def read_file(opts, path, stats):
    '''
    Read the file contents.
    '''
    try:
        while True:
            with open(path, 'rb') as ifp:
                data = ifp.read(bufferSize)
                stat_inc(stats, 'read', len(data))
                return data
    except IOError as exc:
        get_err_fct(opts)('failed to read file "{}": {}'.format(path, exc))
        return None

**Comment by jlinoff** [comment]
You are correct, the code shown would limit the size of the files that the `read_file()` function could handle, but the current version of `read_file()` at line 504 does _not_ have that logic so there is no limit other than the available memory. Because of that, i am going to consider this issue closed. Please let me know if we need to re-open it.

Is it possible that you are referring to an older version of `lock_files.py`? The current version can be found at line 116. It is `1.1.2`.

Here is the current implementation.
```python
def read_file(opts, path, stats):
    '''
    Read the file contents.
    '''
    try:
        with open(path, 'rb') as ifp:
            data = ifp.read()
            stat_inc(stats, 'read', len(data))
            return data
    except IOError as exc:
        get_err_fct(opts)('failed to read file "{}": {}'.format(path, exc))
return None
```
You might consider using the code quoting capabilities of the markdown language to make your code snippets easier to read. See the "Syntax highlighting" section in https://guides.github.com/features/mastering-markdown for details.

**Comment by vinsonpyg** [comment]
Will this feature be added in later versions? I think at least one option can be added on the project.
